import os
import shutil
import tempfile
import subprocess
from pathlib import Path

def test_downstream_path_resolution():
    """
    Tests whether SWT orchestration scripts can be successfully executed
    out-of-the-box inside a consumer workspace after an install.sh physical copy.
    """
    swt_core = Path(__file__).resolve().parents[1]
    install_script = swt_core / "skills" / "swt-link" / "scripts" / "install.sh"
    
    assert install_script.exists(), f"Install script not found at {install_script}"
    
    workspace = swt_core / "demo"
    print(f"\n[Test] Setting up mock downstream workspace at {workspace}")
    
    # Ensure a clean slate
    if workspace.exists():
        shutil.rmtree(workspace)
    workspace.mkdir(parents=True)
    
    try:
        # 1. Initialize as a git repo (needed for task gate arming)
        subprocess.run(["git", "init"], cwd=workspace, check=True, capture_output=True)
        
        # 1.5 Drop in simple README to test non-destructive append
        workspace.joinpath("README.md").write_text("# Initial Fake Project\n")
        
        # 2. Run swt-link physical copy install
        print("[Test] Executing install.sh --clear...")
        subprocess.run(["bash", str(install_script), "--clear", str(workspace)], check=True, capture_output=True)
        
        # Verify agents folder was created
        agents_dir = workspace / ".agents"
        assert agents_dir.exists(), ".agents folder was not created in downstream workspace."
        
        # 3. Simulate swt:init logic (Agent copying templates)
        print("[Test] Simulating swt:init (single-project template)...")
        agents_md_template = swt_core / "skills" / "swt-init" / "templates" / "single-project.md"
        swt_json_template = swt_core / "skills" / "swt-init" / "templates" / "swt.json"
        
        workspace.joinpath("AGENTS.md").write_text(agents_md_template.read_text().replace("{{project_name}}", "Demo Consumer").replace("{{purpose}}", "Testing SWT Downstream"))
        
        # For swt.json, we parse the template and inject swt_home for testing
        import json
        swt_json_data = json.loads(swt_json_template.read_text())
        swt_json_data["swt_home"] = str(swt_core.resolve())
        swt_json_data["mode"] = "protocol"
        swt_json_data["test_command"] = "uv run python3 -m unittest discover -s tests"
        workspace.joinpath("swt.json").write_text(json.dumps(swt_json_data, indent=2))
        
        # 4. Test python engine execution (state.py)
        state_py = agents_dir / "skills" / "swt-flow" / "scripts" / "state.py"
        assert state_py.exists(), f"state.py not found at {state_py}"
        
        print("[Test] Testing state.py decoupled execution...")
        result = subprocess.run(["python3", str(state_py), "--json"], cwd=workspace, capture_output=True, text=True)
        assert result.returncode == 0, f"state.py failed execution in downstream context. Error:\n{result.stderr}"
        
        # 5. Execute Automated Setup / Upgrade (The final checklist item in swt:init)
        task_sh = agents_dir / "skills" / "swt-task" / "scripts" / "task.sh"
        
        print("[Test] Testing automated setup --upgrade...")
        upgrade_res = subprocess.run(["bash", str(task_sh), "setup", "--upgrade"], cwd=workspace, capture_output=True, text=True)
        assert upgrade_res.returncode == 0, f"Upgrade mode failed. Error:\n{upgrade_res.stderr}\n{upgrade_res.stdout}"
        
        # Verify hook was generated
        pre_commit_hook = workspace / ".git" / "hooks" / "pre-commit"
        assert pre_commit_hook.exists(), "pre-commit hook was not armed in downstream workspace."
        hook_content = pre_commit_hook.read_text()
        assert "SWT GATE" in hook_content or "SWT: Physical Gate" in hook_content, "Pre-commit hook does not contain SWT logic."
        
        # Verify README generation
        readme = workspace / "README.md"
        assert readme.exists(), "README.md was not generated by setup."
        assert "Simple Workflow Toolkit (SWT)" in readme.read_text(), "README.md does not contain SWT quick start instructions."
        
        print("[Test] 🚀 All downstream path resolution tests passed successfully!")
    finally:
        # Leave demo folder intact for inspection
        pass

if __name__ == "__main__":
    test_downstream_path_resolution()
