import os
import shutil
import tempfile
import subprocess
from pathlib import Path

def test_downstream_path_resolution():
    """
    Tests whether SWT orchestration scripts can be successfully executed
    out-of-the-box inside a consumer workspace after an install.sh physical copy.
    """
    swt_core = Path(__file__).resolve().parents[1]
    install_script = swt_core / "skills" / "swt-link" / "scripts" / "install.sh"
    
    assert install_script.exists(), f"Install script not found at {install_script}"
    
    workspace = swt_core / "demo"
    print(f"\n[Test] Setting up mock downstream workspace at {workspace}")
    
    # Ensure a clean slate
    if workspace.exists():
        shutil.rmtree(workspace)
    workspace.mkdir(parents=True)
    
    try:
        # 1. Initialize as a git repo (needed for task gate arming)
        subprocess.run(["git", "init"], cwd=workspace, check=True, capture_output=True)
        
        # 2. Run swt-link physical copy install
        print("[Test] Executing install.sh --clear...")
        subprocess.run(["bash", str(install_script), "--clear", str(workspace)], check=True, capture_output=True)
        
        # Verify agents folder was created
        agents_dir = workspace / ".agents"
        assert agents_dir.exists(), ".agents folder was not created in downstream workspace."
        
        # 3. Test python engine execution (state.py)
        state_py = agents_dir / "skills" / "swt-flow" / "scripts" / "state.py"
        assert state_py.exists(), f"state.py not found at {state_py}"
        
        print("[Test] Testing state.py decoupled execution...")
        result = subprocess.run(["python3", str(state_py), "--json"], cwd=workspace, capture_output=True, text=True)
        assert result.returncode == 0, f"state.py failed execution in downstream context. Error:\n{result.stderr}"
        
        # 4. Test task.sh setup (Hook arming)
        task_sh = agents_dir / "skills" / "swt-task" / "scripts" / "task.sh"
        assert task_sh.exists(), f"task.sh not found at {task_sh}"
        
        print("[Test] Testing task.sh setup decoupled execution...")
        subprocess.run(["bash", str(task_sh), "setup"], cwd=workspace, check=True, capture_output=True)
        
        pre_commit_hook = workspace / ".git" / "hooks" / "pre-commit"
        assert pre_commit_hook.exists(), "pre-commit hook was not armed in downstream workspace."
        
        # Check that it appended the hook successfully without crashing
        hook_content = pre_commit_hook.read_text()
        assert "SWT GATE" in hook_content or "SWT: Physical Gate" in hook_content, "Pre-commit hook does not contain SWT logic."
        
        # Verify README generation
        readme = workspace / "README.md"
        assert readme.exists(), "README.md was not generated by setup."
        assert "Simple Workflow Toolkit (SWT)" in readme.read_text(), "README.md does not contain SWT quick start instructions."
        
        # 5. Test UPGRADE Mode
        print("[Test] Testing task.sh setup --upgrade execution...")
        
        # We need a dummy swt.json to ensure upgrade can find swt_home (conforming to the schema)
        swt_json = workspace / "swt.json"
        import json
        conforming_json = {
            "_description": "See CONFIG.md for field definitions",
            "mode": "protocol",
            "test_command": "uv run python3 -m unittest discover -s tests",
            "ritual_gates": {
                "ballmer_heartbeat": True,
                "phase_order_enforcement": True,
                "hitl_approval": True
            },
            "swt_home": str(swt_core.resolve())
        }
        swt_json.write_text(json.dumps(conforming_json, indent=2))
        
        upgrade_res = subprocess.run(["bash", str(task_sh), "setup", "--upgrade"], cwd=workspace, capture_output=True, text=True)
        assert upgrade_res.returncode == 0, f"Upgrade mode failed. Error:\n{upgrade_res.stderr}\n{upgrade_res.stdout}"
        
        print("[Test] 🚀 All downstream path resolution tests passed successfully!")
    finally:
        # Leave demo folder intact for inspection
        pass

if __name__ == "__main__":
    test_downstream_path_resolution()
